E-ChargerInternational/Controllers/StotelesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EChargerInternational.Controllers
{
    public class StotelesController : Controller
    {
        // GET: Stoteles
        public ActionResult Index(int id)
        {
            return View(id);
        }

        // GET: Stoteles/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Stoteles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stoteles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Stoteles/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Stoteles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Stoteles/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Stoteles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

E-ChargerInternational/Views/Stoteles/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

E-ChargerInternational/Views/Stoteles/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h2>Ar tikrai?</h2>
<div><a href="@Url.Action("Index", "Stoteles")">Taip</a></div><div><a href="@Url.Action("Index", "Stoteles")">Ne</a></div>

E-ChargerInternational/Views/Stoteles/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

E-ChargerInternational/Views/Stoteles/Index.cshtml
@model int  
@{
    ViewData["Title"] = "Index";
}

<h2>Stotelės</h2>

<div>Čia bus stotelės, priklausančios aikštelei @Model</div> <div><a href="#">Filtruoti</a></div>
<table class="table">
    <tr>
        <td>Pavadinimas</td><td><a href="@Url.Action("Delete", "Stoteles")">Trinti</a> <a href="@Url.Action("Edit", "Stoteles")">Keisti</a></td>
        </tr>
    </table>