E-ChargerInternational/Controllers/AikstelesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EChargerInternational.EChargerInternational;

namespace EChargerInternational.Controllers
{
    public class AikstelesController : Controller
    {
        private readonly EChargerInternationalContext _context;

        public AikstelesController(EChargerInternationalContext context)
        {
            _context = context;
        }

        // GET: Aiksteles
        public async Task<IActionResult> Index()
        {
            var eChargerInternationalContext = _context.Aikstele.Include(a => a.FkKlientasidKlientasNavigation);
            return View(await eChargerInternationalContext.ToListAsync());
        }

        // GET: Aiksteles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aikstele = await _context.Aikstele
                .Include(a => a.FkKlientasidKlientasNavigation)
                .FirstOrDefaultAsync(m => m.IdAikstele == id);
            if (aikstele == null)
            {
                return NotFound();
            }

            return View(aikstele);
        }

        // GET: Aiksteles/Create
        public IActionResult Create()
        {
            ViewData["FkKlientasidKlientas"] = new SelectList(_context.Klientas, "IdKlientas", "Aprasymas");
            return View();
        }

        // POST: Aiksteles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Pavadinimas,TelefonoNumeris,DarboPradzia,DarboPabaiga,Saugoma,ElektrosKaina,PapildomasMokestis,PapildomoMokescioAprasymas,Miestas,Gatve,NamoNr,KoordinateX,KoordinateY,PastoKodas,Aprasymas,IdAikstele,FkKlientasidKlientas")] Aikstele aikstele)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aikstele);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkKlientasidKlientas"] = new SelectList(_context.Klientas, "IdKlientas", "Aprasymas", aikstele.FkKlientasidKlientas);
            return View(aikstele);
        }

        // GET: Aiksteles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aikstele = await _context.Aikstele.FindAsync(id);
            if (aikstele == null)
            {
                return NotFound();
            }
            ViewData["FkKlientasidKlientas"] = new SelectList(_context.Klientas, "IdKlientas", "Aprasymas", aikstele.FkKlientasidKlientas);
            return View(aikstele);
        }

        // POST: Aiksteles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Pavadinimas,TelefonoNumeris,DarboPradzia,DarboPabaiga,Saugoma,ElektrosKaina,PapildomasMokestis,PapildomoMokescioAprasymas,Miestas,Gatve,NamoNr,KoordinateX,KoordinateY,PastoKodas,Aprasymas,IdAikstele,FkKlientasidKlientas")] Aikstele aikstele)
        {
            if (id != aikstele.IdAikstele)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aikstele);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AiksteleExists(aikstele.IdAikstele))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkKlientasidKlientas"] = new SelectList(_context.Klientas, "IdKlientas", "Aprasymas", aikstele.FkKlientasidKlientas);
            return View(aikstele);
        }

        // GET: Aiksteles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aikstele = await _context.Aikstele
                .Include(a => a.FkKlientasidKlientasNavigation)
                .FirstOrDefaultAsync(m => m.IdAikstele == id);
            if (aikstele == null)
            {
                return NotFound();
            }

            return View(aikstele);
        }

        // POST: Aiksteles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aikstele = await _context.Aikstele.FindAsync(id);
            _context.Aikstele.Remove(aikstele);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AiksteleExists(int id)
        {
            return _context.Aikstele.Any(e => e.IdAikstele == id);
        }
    }
}

E-ChargerInternational/Controllers/AsmeninesStotelesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EChargerInternational.Controllers
{
    public class AsmeninesStotelesController : Controller
    {
        // GET: AsmeninesStoteles
        public ActionResult Index()
        {
            return View();
        }

        // GET: AsmeninesStoteles/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AsmeninesStoteles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AsmeninesStoteles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AsmeninesStoteles/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AsmeninesStoteles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AsmeninesStoteles/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AsmeninesStoteles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

E-ChargerInternational/Controllers/NaudotojaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EChargerInternational.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_ChargerInternational.Controllers
{
    public class NaudotojaiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Naudotojas user)
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Naudotojas user)
        {
            return View();
        }
        public IActionResult BlockUser(int id)
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
    }
}

E-ChargerInternational/Controllers/RezervacijosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace E_ChargerInternational.Controllers
{
    public class RezervacijosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(object Rezervacija)
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(object Rezervacija)
        {
            return View();
        }
        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(object Rezervacija)
        {
            return View();
        }
    }
}

E-ChargerInternational/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_ChargerInternational</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body background="C:\Users\erikun\Documents\Shit and stuff\E-ChargerInternational\E-ChargerInternational\Content\Tesla.jpg">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">E_Charger International</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    </li>
                    <li><a asp-area="" asp-controller="Aiksteles" asp-action="Index">Aikštelės</a></li>
                    <li><a asp-area="" asp-controller="Rezervacijos" asp-action="Index">Rezervacijos</a></li>
                    <li><a asp-area="" asp-controller="AsmeninesStoteles" asp-action="Index">Asmeninės stotelės</a></li>
                    <li><a asp-area="" asp-controller="Naudotojai" asp-action="Index">Naudotojų sąrašas</a></li>
                    <li><a asp-area="" asp-controller="Naudotojai" asp-action="Login">Prisijungti</a></li>
                    <li><a asp-area="" asp-controller="Naudotojai" asp-action="Register">Registruotis</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Kontaktai</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - E_ChargerInternational</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>